### PR TITLE
Fix automagic dependencies

### PR DESCRIPTION
**Pull request by Hummer12007**
This patch by Gentoo fixes automagic dependencies in mono-tools (see https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies for reference and rationale).

### CODE REVIEW

**Comment by akoeplinger** [comment]
Looks good to me. Since you mentioned Gentoo, do you know which license the patch is under and who wrote it originally?

**Comment by Hummer12007** [comment]
The patch is written by @mpkh, and is, like stuff in the Portage 3, licensed under GPL v2. (see the header https://github.com/gentoo/dotnet/blob/master/dev-util/mono-tools/mono-tools-9999.ebuild )

**Comment by mpkh** [comment]
@Hummer12007 I think originally by @alistair

**Comment by akoeplinger** [comment]
Checked with Miguel, for configure.in we're OK with GPL.

**Pull request merged**
